root: ./docs/book/

structure:
  readme: introduction.md
  summary: toc.md

redirects:
  how-to/customize-docker-builds/use-code-repositories-to-speed-up-docker-build-times: how-to/infrastructure-deployment/customize-docker-builds/how-to-reuse-builds.md
  reference/migration-guide: how-to/manage-the-zenml-server/migration-guide/migration-guide.md
  reference/migration-guide/migration-zero-twenty: how-to/manage-the-zenml-server/migration-guide/migration-zero-twenty.md
  reference/migration-guide/migration-zero-thirty: how-to/manage-the-zenml-server/migration-guide/migration-zero-thirty.md
  reference/migration-guide/migration-zero-forty: how-to/manage-the-zenml-server/migration-guide/migration-zero-forty.md
  reference/migration-guide/migration-zero-sixty: how-to/manage-the-zenml-server/migration-guide/migration-zero-sixty.md

  getting-started/deploying-zenml/manage-the-deployed-services/upgrade-the-version-of-the-zenml-server: how-to/manage-the-zenml-server/upgrade-zenml-server.md
  getting-started/deploying-zenml/manage-the-deployed-services/troubleshoot-your-deployed-server: how-to/manage-the-zenml-server/troubleshoot-your-deployed-server.md
  how-to/stack-deployment/implement-a-custom-integration: how-to/contribute-to-zenml/implement-a-custom-integration.md
  how-to/setting-up-a-project-repository/best-practices: how-to/project-setup-and-management/setting-up-a-project-repository/set-up-repository.md
  getting-started/zenml-pro/system-architectures: getting-started/system-architectures.md
  how-to/build-pipelines/name-your-pipeline-and-runs: how-to/pipeline-development/build-pipelines/name-your-pipeline-runs.md

  # Project Setup redirects
  how-to/setting-up-a-project-repository/README: how-to/project-setup-and-management/setting-up-a-project-repository/README.md
  how-to/setting-up-a-project-repository/set-up-repository: how-to/project-setup-and-management/setting-up-a-project-repository/set-up-repository.md
  how-to/setting-up-a-project-repository/connect-your-git-repository: how-to/project-setup-and-management/setting-up-a-project-repository/connect-your-git-repository.md
  how-to/setting-up-a-project-repository/using-project-templates: how-to/project-setup-and-management/setting-up-a-project-repository/using-project-templates.md
  how-to/setting-up-a-project-repository/create-your-own-template: how-to/project-setup-and-management/setting-up-a-project-repository/create-your-own-template.md
  how-to/setting-up-a-project-repository/shared-components-for-teams: how-to/project-setup-and-management/setting-up-a-project-repository/shared-components-for-teams.md
  how-to/setting-up-a-project-repository/stacks-pipelines-models: how-to/project-setup-and-management/setting-up-a-project-repository/stacks-pipelines-models.md
  how-to/setting-up-a-project-repository/access-management: how-to/project-setup-and-management/setting-up-a-project-repository/access-management.md

  how-to/develop-locally/README: how-to/project-setup-and-management/develop-locally/README.md
  how-to/develop-locally/local-prod-pipeline-variants: how-to/project-setup-and-management/develop-locally/local-prod-pipeline-variants.md
  how-to/develop-locally/keep-your-dashboard-server-clean: how-to/project-setup-and-management/develop-locally/keep-your-dashboard-server-clean.md

  how-to/connecting-to-zenml/README: how-to/project-setup-and-management/connecting-to-zenml/README.md
  how-to/connecting-to-zenml/connect-in-with-your-user-interactive: how-to/project-setup-and-management/connecting-to-zenml/connect-in-with-your-user-interactive.md
  how-to/connecting-to-zenml/connect-with-a-service-account: how-to/project-setup-and-management/connecting-to-zenml/connect-with-a-service-account.md
