root: ./docs/book/

structure:
  readme: introduction.md
  summary: toc.md

redirects:
  how-to/stack-deployment/implement-a-custom-integration.md: how-to/contribute-to-zenml/implement-a-custom-integration.md