# Changes here will be overwritten by Copier
_commit: 2024.10.30-3-g52bf387
_src_path: gh:zenml-io/template-starter
email: info@zenml.io
full_name: ZenML GmbH
open_source_license: apache
project_name: ZenML Starter
version: 0.1.0
