---
name: Publish Cloud Stack Templates
on:
  workflow_call:
  workflow_dispatch:
jobs:
  publish_stack_templates:
    name: Publish Cloud Stack Templates
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      # Setup AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::715803424590:role/gh-action-role-zenml-stack-cf-templates
          aws-region: eu-central-1
      # Publish the CloudFormation template to S3
      - name: Push CloudFormation template to S3
        run: |-
          aws s3 cp infra/aws/aws-ecr-s3-sagemaker.yaml s3://zenml-cf-templates/aws-ecr-s3-sagemaker.yaml
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_CLOUDBUILD_EMAIL }}
          service_account_key: ${{ secrets.GCP_CLOUDBUILD_KEY }}
          project_id: ${{ secrets.GCP_CLOUDBUILD_PROJECT }}
      # Publish the Deployment Manager function code to GCS
      - name: Push Deployment Manager function to GCS
        run: |-
          zip -j gcp-dm-stack-register.zip infra/gcp/main.py infra/gcp/requirements.txt
          gsutil cp gcp-dm-stack-register.zip gs://zenml-public-bucket/zenml-gcp-dm-templates/
